/// Flutter icons AppIcons
/// Copyright (C) 2023 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  AppIcons
///      fonts:
///       - asset: fonts/AppIcons.ttf
///
///
///
library;

import 'package:flutter/widgets.dart';

class AppIcons {
  AppIcons._();

  static const _kFontFam = 'AppIcons';
  static const String? _kFontPkg = null;

  static const IconData blog_filled = IconData(0xe800, fontFamily: _kFontFam);
  static const IconData blog_outlined = IconData(0xe801, fontFamily: _kFontFam);
  static const IconData calendar_filled =
      IconData(0xe802, fontFamily: _kFontFam);
  static const IconData calendar_outlined =
      IconData(0xe803, fontFamily: _kFontFam);
  static const IconData consultations_filled =
      IconData(0xe804, fontFamily: _kFontFam);
  static const IconData consultations_outlined =
      IconData(0xe805, fontFamily: _kFontFam);
  static const IconData home_filled = IconData(0xe806, fontFamily: _kFontFam);
  static const IconData home_outlined = IconData(0xe807, fontFamily: _kFontFam);
  static const IconData ic_arrow_down = IconData(0xe808, fontFamily: _kFontFam);
  static const IconData ic_arrow_up = IconData(0xe809, fontFamily: _kFontFam);
  static const IconData ic_back_ios = IconData(0xe80a, fontFamily: _kFontFam);
  static const IconData ic_call_end_filled =
      IconData(0xe80b, fontFamily: _kFontFam);
  static const IconData ic_call_pick_filled =
      IconData(0xe80c, fontFamily: _kFontFam);
  static const IconData ic_camera_filled =
      IconData(0xe80d, fontFamily: _kFontFam);
  static const IconData ic_chat_filled =
      IconData(0xe80e, fontFamily: _kFontFam);
  static const IconData ic_chat_outlined =
      IconData(0xe80f, fontFamily: _kFontFam);
  static const IconData ic_cross_round =
      IconData(0xe810, fontFamily: _kFontFam);
  static const IconData ic_cross = IconData(0xe811, fontFamily: _kFontFam);
  static const IconData ic_emoji = IconData(0xe812, fontFamily: _kFontFam);
  static const IconData ic_gallery = IconData(0xe813, fontFamily: _kFontFam);
  static const IconData ic_logout = IconData(0xe814, fontFamily: _kFontFam);
  static const IconData ic_master_card =
      IconData(0xe815, fontFamily: _kFontFam);
  static const IconData ic_mic_off_filled =
      IconData(0xe816, fontFamily: _kFontFam);
  static const IconData ic_notes_round =
      IconData(0xe817, fontFamily: _kFontFam);
  static const IconData ic_send_filled =
      IconData(0xe818, fontFamily: _kFontFam);
  static const IconData ic_video_cam = IconData(0xe819, fontFamily: _kFontFam);
  static const IconData ic_video_filled =
      IconData(0xe81a, fontFamily: _kFontFam);
  static const IconData ic_video_outline =
      IconData(0xe81b, fontFamily: _kFontFam);
  static const IconData notificatins_filled =
      IconData(0xe81c, fontFamily: _kFontFam);
  static const IconData notifications_outlined =
      IconData(0xe81d, fontFamily: _kFontFam);
  static const IconData walled_outlined =
      IconData(0xe81e, fontFamily: _kFontFam);
  static const IconData wallet_filled = IconData(0xe81f, fontFamily: _kFontFam);
  static const IconData wallet_outlined =
      IconData(0xe820, fontFamily: _kFontFam);
  static const IconData ic_calendar = IconData(0xe821, fontFamily: _kFontFam);
  static const IconData ic_chat_outlined_1 =
      IconData(0xe822, fontFamily: _kFontFam);
  static const IconData ic_clock_time = IconData(0xe823, fontFamily: _kFontFam);
  static const IconData ic_hourglass_time =
      IconData(0xe824, fontFamily: _kFontFam);
  static const IconData ic_logout_outlined =
      IconData(0xe825, fontFamily: _kFontFam);
  static const IconData ic_search = IconData(0xe826, fontFamily: _kFontFam);
  static const IconData ic_video_outlined_rounded =
      IconData(0xe827, fontFamily: _kFontFam);
  static const IconData ic_wallet_plus_outlined =
      IconData(0xe828, fontFamily: _kFontFam);
}
